name: Build and Deploy to Firebase Hosting on merge

'on':
  push:
    branches:
      - main

jobs:
  build_and_deploy_frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./discord-auth-frontend
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14' # Ensure this version matches your project requirements
      - name: Install dependencies
        run: yarn install
      - name: Build
        run: yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_DISCORD_TWITTER_AUTH_DEMO }}'
          channelId: live
          projectId: discord-twitter-auth-demo
